// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV842HfGQzdijvPK4LTil9W9IhEqYLfuM',
    appId: '1:41314805136:web:28224d87442c87fc9b7f15',
    messagingSenderId: '41314805136',
    projectId: 'locallend-f965e',
    authDomain: 'locallend-f965e.firebaseapp.com',
    storageBucket: 'locallend-f965e.firebasestorage.app',
    measurementId: 'G-VY2XLZBKF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsy3BGwwRevgMFGtIKDR-cbw8aKa4stwg',
    appId: '1:41314805136:android:d1d80207fe7575e79b7f15',
    messagingSenderId: '41314805136',
    projectId: 'locallend-f965e',
    storageBucket: 'locallend-f965e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc1KnN3rA7aPedyKccax6mKwEbPjcKub0',
    appId: '1:41314805136:ios:056d1cbb54df19989b7f15',
    messagingSenderId: '41314805136',
    projectId: 'locallend-f965e',
    storageBucket: 'locallend-f965e.firebasestorage.app',
    iosBundleId: 'com.example.locallend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc1KnN3rA7aPedyKccax6mKwEbPjcKub0',
    appId: '1:41314805136:ios:056d1cbb54df19989b7f15',
    messagingSenderId: '41314805136',
    projectId: 'locallend-f965e',
    storageBucket: 'locallend-f965e.firebasestorage.app',
    iosBundleId: 'com.example.locallend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV842HfGQzdijvPK4LTil9W9IhEqYLfuM',
    appId: '1:41314805136:web:b364f340ee849ec99b7f15',
    messagingSenderId: '41314805136',
    projectId: 'locallend-f965e',
    authDomain: 'locallend-f965e.firebaseapp.com',
    storageBucket: 'locallend-f965e.firebasestorage.app',
    measurementId: 'G-N2GLPL1X33',
  );
}
